buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.google.com" }
        maven { url "https://github.com/ionic-team/capacitor-android" }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.1.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.20"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.google.com" }
        // Repositorio oficial de Capacitor
        maven { url "https://cdn.jsdelivr.net/npm/@capacitor/android/" }
        maven { url "https://ionic-team.github.io/capacitor/maven/" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
